[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
nixpacksConfigPath = "nixpacks.toml"
